### ISSUE TITLE
rustup for nightly, requires feature

### ISSUE THREAD

**Issue by viperscape** [bluss/fixedbitset#1]
```
Compiling fixedbitset v0.0.2
...
fixedbitset-0.0.2\src\lib.rs:34:24: 34:42 error: use of unstable library feature 'collections'
fixedbitset-0.0.2\src\lib.rs:97:56: 97:56 help: add #![feature(collections)] to the crate attributes to enable
```

Saw this when compiling petgraph, giving you a heads up!

**Comment by bluss** [comment]
Thank you.

**Comment by bluss** [comment]
Tested 14/4/2015 nightly too, it must have been reported from an old nightly.

Thanks anyway, and feel free to report other issues if you find any!

**Comment by viperscape** [comment]
ah yes, sorry for the misdirection! the windows packaged installers (msi vs exe) are different for rust nightly, my currently installed version was never being updated! :-\
