### ISSUE TITLE
Implement some way to `BitOr` without copying

### ISSUE THREAD

**Issue by swolchok** [bluss/fixedbitset#23]
`FixedBitSet`'s `BitOr` implementation requires copying the underlying data, since it returns a new `FixedBitSet` (see https://play.rust-lang.org/?gist=0b8e747fc39a65088ac2403e387dde2e&version=stable&mode=release&edition=2015 for demonstration of copy -- `FixedBitSet::bitor` doesn't get inlined, so the copy certainly isn't getting optimized away) Seems like it would be nice to have a `union_with(&mut self, rhs: &FixedBitSet)` function that could do this operation without copying.

**Comment by bluss** [comment]
Let's implement at least the assign-ops for this too
