### ISSUE TITLE
Add count_ones_to_offset function

### ISSUE THREAD

**Issue by fuine** [bluss/fixedbitset#4]
I have implemented function: `fn count_ones_to_offset(&self, offset: usize) -> usize`. I would like to add it to this crate, but when I asked @bluss about it, he suggested that maybe this function should take Range as argument. Example usage below:

```
    let mut fb = FixedBitSet::with_capacity(15);
    fb.set(11, true);
    fb.set(7, true);
    assert_eq!(fb.count_ones_to_offset(6), 0);
    assert_eq!(fb.count_ones_to_offset(7), 1);
    assert_eq!(fb.count_ones_to_offset(11), 2);
```

**Comment by bluss** [comment]
`fb.count_ones(..), fb.count_ones(..6), fb.count_ones(3..11)` seems like the most powerful and simple to use API. However, that would require some kind of range trait. You can copy the code from crate odds.

**Comment by bluss** [comment]
Or just implement it for `Range<usize>` for now.

**Comment by fuine** [comment]
I thought about using [this crate](https://docs.rs/num-traits/0.1.36/num_traits/) like so:
`fn count_ones<T: Num>(&self, r: Range<T>) -> usize`. What do you think?

**Comment by bluss** [comment]
Absolutely not. Nothing personal, but indices are only `usize` in Rust, we don't need numerical traits.

**Comment by fuine** [comment]
Sure. I think i will use the trait from odds, do you want me to copy the implementation over or include odds as dependency? Also i think that in the long term we could migrate to https://github.com/rust-lang/rust/issues/30877 if it ever stabilizes

**Comment by bluss** [comment]
copy
